version: '3.9'

services:

  datadog-agent:
    image: datadog/agent:7
    environment:
      - DD_API_KEY=
      - DD_SITE=ap1.datadoghq.com
      - DD_SERVICE=test01
      - DD_ENV=test-env
      - DD_LOG_LEVEL=info # warn
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
      - "4317:4317"
